### ISSUE TITLE
Give middleware function a name

### ISSUE THREAD

**Issue by daniellockyer** [azu/express-lazy-router#7]
Hey @azu! 🙂 

Would it be possible to give the middleware function a name? Tools such as New Relic report it as `<anonymous>` otherwise, which makes it difficult in tracking down the source.

https://github.com/azu/express-lazy-router/blob/e70a4ad22b7ae026345cd49e31b186a3ce0db7e6/src/express-lazy-router.ts#L50

**Comment by azu** [comment]
Yes, it is possible and reasonable.

```diff
-        lazyRouter.use((req, res, next) => {
+        lazyRouter.use(function lazyRouterHandler(req, res, next) {
```

**Comment by daniellockyer** [comment]
Exactly! Shall I PR this or will you handle?

**Comment by daniellockyer** [comment]
PR sent 🙂

**Comment by azu** [comment]
Fixed in https://github.com/azu/express-lazy-router/releases/tag/v1.0.6

Thanks for PR!
